### ISSUE TITLE
Suggestion from func_msgboard

### ISSUE THREAD

**Issue by dumptruckDS** [glhrmfrts/q1compile#10]
[https://www.celephais.net/board/view_thread.php?id=61912&start=11](url)

re: hard coded file names and ordering

> Seems weird that these tools are hardcoded to only accept certain filenames (such as qbsp, light and vis)... I think it'd be better if you could have different file names. Also if you had the ability to swap the compile order, namely vis and light, then you could also have compatibility with Q2.

**Comment by glhrmfrts** [comment]
Thanks for relaying this here, I didn't check func for a while. 

As I said there, these are good suggestions, so I'll start working on them as soon as I can to include them in the next update!

**Comment by glhrmfrts** [comment]
Implemented in v0.7.
