### ISSUE TITLE
Feature Request - Load last used preset at launch

### ISSUE THREAD

**Issue by dumptruckDS** [glhrmfrts/q1compile#2]
Would be nice to have your preset saved and available without having to load it each session.

**Comment by glhrmfrts** [comment]
@dumptruckDS You mean the compiler flags preset right? That sounds like a bug actually if it isn't loading it automatically. Please note that you have to save the Config (Ctrl+S) when you select a different preset in order to persist your choice.

But if that's the case, now I'm wondering if it should save automatically when the user changes something...

**Comment by dumptruckDS** [comment]
When I stop and start the application it's blank every time. I am loading my preferred config from the file menu, compiling, exiting and I get what  you see in the attached screenshot when re-opening.
![image](https://user-images.githubusercontent.com/16103297/87691507-7f402a00-c73f-11ea-8ea1-1c4c74aef5aa.png)

**Comment by glhrmfrts** [comment]
Welp, that's definitely a bug. Could you please check if the following folder exists in your main drive: 

`C:\Users\{YOUR_USERNAME}\AppData\Roaming\Quake 1 Compile GUI`

If it does, there should be a `config.cfg` file inside of it, and could you upload that so I can see? Or at least let me know if it looks like this:

```
$loaded_config "C:/QuakeDev/maps_id1/machinery_id1.cfg"
$last_import_preset_location "C:/code"
$last_export_preset_location "C:/code"
$recent_config "C:/QuakeDev/maps_progs_dump/q1compile_config_sunlessemp-beta5.cfg"
$recent_config "C:/QuakeDev/maps_id1/machinery_id1.cfg"
$recent_config "C:/QuakeDev/maps_id1/machinery_id1_q15.cfg"
$recent_config "C:/QuakeDev/maps_id1/machinery_id1_new_file.cfg"
$recent_config "C:/QuakeDev/maps_id1/machinery_id1_another_file.cfg"
$tool_preset "Fast Custom Test 2"
$tool_preset_qbsp_args ""
$tool_preset_light_args "-fast -nice"
$tool_preset_vis_args "-fast -nice"
$tool_preset_qbsp_enabled true
$tool_preset_light_enabled true
$tool_preset_vis_enabled true
```

Also, there should be a `q1compile_err.txt` file in the application folder, if you can upload that as well it will be a huge help!

**Comment by glhrmfrts** [comment]
This should be solved in [v0.4](https://github.com/glhrmfrts/q1compile/releases/tag/v0.4). I'll wait confirmation to close the issue though.

**Comment by dumptruckDS** [comment]
Oh my god. I am so sorry I missed this message. Please ping me on Discord if I can help any further.

**Comment by glhrmfrts** [comment]
No problem, I'll close this issue since it's fixed in recent versions, feel free to re-open if for some reason it still doesn't work for you.
